
package Interfaz;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfTable;
import com.lowagie.text.pdf.PdfWriter;
//import com.sun.org.apache.xml.internal.serialize.OutputFormat;
import com.sun.org.apache.xml.internal.serialize.XMLSerializer;
//import com.sun.xml.internal.txw2.Document;
//import com.lowagie.text.Document;

import java.awt.Color;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.System.out;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
//import com.itextpdf.text.Document;

/**
 *min
 * @author juliana
 */
public class Historial extends javax.swing.JDialog {

    String Code="";
    DefaultTableModel modelo;
    int resul;
    int num1,num2;
    Object m[]=new Object[7];
    int  sumatoria;
    int  sumatoria1=0;
    String total1;
    
    public Historial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         getContentPane().setBackground(new java.awt.Color(178, 34, 34));
         Document doc;
        cargar();
        //jtabla.setDefaultRenderer(Object.class, new TableCellRendererColor());
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void cargar()
    {
        try{
    		Class.forName("com.mysql.jdbc.Driver");
    		Connection conexion = DriverManager.getConnection("jdbc:mysql://sql10.freesqldatabase.com:3306/sql10292471", "sql10292471", "5smwscQGBg");
    		Statement s = conexion.createStatement();
    		ResultSet r = s.executeQuery("select * from productos;");
                jCPRODUCTOS.removeAllItems();
                while(r.next())
                {
    		//jcombo.addItem(r.getString("placa")+" "+(r.getString("Propietario")));
                    jCPRODUCTOS.addItem(r.getString("nombreProd1"));
                }
    		conexion.close();
    		}
    	catch(Exception x)
        {
    		JOptionPane.showMessageDialog(null,"Error "+x);
    	}
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jTPrecio = new javax.swing.JTextField();
        jlFoto = new javax.swing.JLabel();
        jbbuscar = new javax.swing.JButton();
        jTCantidad = new javax.swing.JTextField();
        jlcliente1 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jBAGREGARCARRO = new javax.swing.JButton();
        jlcliente2 = new javax.swing.JLabel();
        jGENERARFACTURA = new javax.swing.JButton();
        jCPRODUCTOS = new javax.swing.JComboBox<>();
        jlcodigo1 = new javax.swing.JLabel();
        jtotalCampo = new javax.swing.JLabel();
        jtotalCampo1 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jTNombreCliente = new javax.swing.JTextField();
        jlcodigo2 = new javax.swing.JLabel();
        jTNIT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("                                                                                                                                FACTURAR PRODUCTO");

        jblimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes 2/1462650096_edit-clear.png"))); // NOI18N
        jblimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimpiarActionPerformed(evt);
            }
        });

        jtabla.setAutoCreateRowSorter(true);
        jtabla.setBackground(new java.awt.Color(255, 204, 51));
        jtabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtabla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    CÓDIGO", "    NOMBRE DEL PRODUCTO", "    PRECIO", "    CANTIDAD", "    TOTAL", "    ELIMINAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtabla.setAlignmentX(1.0F);
        jtabla.setAlignmentY(1.0F);
        jtabla.setColumnSelectionAllowed(true);
        jtabla.setGridColor(new java.awt.Color(0, 0, 0));
        jtabla.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(jtabla);
        jtabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlFoto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlFoto.setForeground(new java.awt.Color(255, 255, 255));

        jbbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes 2/1465798029_system-search.png"))); // NOI18N
        jbbuscar.setText("PRODUCTOS");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jTCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlcliente1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlcliente1.setForeground(new java.awt.Color(255, 255, 255));
        jlcliente1.setText("CANTIDAD #");

        jBAGREGARCARRO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBAGREGARCARRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes 2/agregar.png"))); // NOI18N
        jBAGREGARCARRO.setText(" AGREGAR A LA FACTURA");
        jBAGREGARCARRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAGREGARCARROActionPerformed(evt);
            }
        });

        jlcliente2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlcliente2.setForeground(new java.awt.Color(255, 255, 255));
        jlcliente2.setText("PRECIO $");

        jGENERARFACTURA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jGENERARFACTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes 2/1465894000_15.png"))); // NOI18N
        jGENERARFACTURA.setText("GENERAL FACTURA");
        jGENERARFACTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGENERARFACTURAActionPerformed(evt);
            }
        });

        jCPRODUCTOS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCPRODUCTOS.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jCPRODUCTOSComponentHidden(evt);
            }
        });
        jCPRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPRODUCTOSActionPerformed(evt);
            }
        });

        jlcodigo1.setBackground(new java.awt.Color(255, 255, 255));
        jlcodigo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlcodigo1.setForeground(new java.awt.Color(255, 255, 255));
        jlcodigo1.setText("NOMBRE DEL PRODUCTO");

        jtotalCampo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtotalCampo.setText("TOTAL $");

        jtotalCampo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes 2/checkBox.png"))); // NOI18N
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jTNombreCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlcodigo2.setBackground(new java.awt.Color(255, 255, 255));
        jlcodigo2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jlcodigo2.setForeground(new java.awt.Color(255, 255, 255));
        jlcodigo2.setText("NOMBRE DEL CLIENTE");

        jTNIT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jtotalCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtotalCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jGENERARFACTURA)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlcliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCPRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jlcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jbbuscar)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAGREGARCARRO)))))
                .addContainerGap(879, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlcodigo1)
                            .addComponent(jCPRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbbuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jblimpiar)
                                        .addComponent(jbCancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlcliente2)
                                            .addComponent(jlcliente1)
                                            .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jBAGREGARCARRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlcodigo2)
                            .addComponent(jTNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtotalCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGENERARFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtotalCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimpiarActionPerformed
       jtotalCampo1.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jtabla.getModel();
            while(modelo.getRowCount()>0)modelo.removeRow(0);
    }//GEN-LAST:event_jblimpiarActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed


        ImageIcon foto;
        InputStream is;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = DriverManager.getConnection("jdbc:mysql://sql10.freesqldatabase.com:3306/sql10292471", "sql10292471", "5smwscQGBg");
            Statement s = conexion.createStatement();
            ResultSet r = s.executeQuery("select nitProd1,precioProd1,foto1 from productos where nombreProd1="+"'"+jCPRODUCTOS.getSelectedItem()+"'");
            System.out.println(" combo:   "+jCPRODUCTOS.getSelectedItem());
            while(r.next()){

                jTNIT.setText(r.getObject(1)+"");
                jTPrecio.setText(r.getObject(2)+"");
                
                jlFoto.setText(r.getObject(3)+"");
               
                
                foto=new ImageIcon(jlFoto.getText());
                
                

                Image img= foto.getImage();
                Image newimg=img.getScaledInstance(140, 170,java.awt.Image.SCALE_SMOOTH);

                ImageIcon newIcon=new ImageIcon(newimg);
                jlFoto.setIcon(newIcon);

            }
            conexion.close();

        }

        catch(Exception x)
        {
            JOptionPane.showMessageDialog(null," CAMPOS VACIOS "+x);
        }

        
        
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jBAGREGARCARROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAGREGARCARROActionPerformed
//jcombo.removeAllItems();       
        try{
                 modelo= (DefaultTableModel)this.jtabla.getModel();
                 
       num1=Integer.parseInt(jTPrecio.getText());
       num2=Integer.parseInt(jTCantidad.getText());
       
        resul=num1*num2;
                    
        
                    m[0]=jTNIT.getText();
                    m[1]=jCPRODUCTOS.getSelectedItem();
                    m[2]=jTPrecio.getText();
                    m[3]=jTCantidad.getText();
                    m[4]=resul;
                   // m[4]=r.getString(5);
                    
                        modelo.addRow(m);   
                
    		}
    	catch(Exception x)
        {
    		JOptionPane.showMessageDialog(null," TIENE CAMPOS VACIOS ");
    	}
        jTNIT.setText("");
        jTCantidad.setText("");
                jTPrecio.setText("");
                jlFoto.setText("");
    }//GEN-LAST:event_jBAGREGARCARROActionPerformed

    private void jGENERARFACTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGENERARFACTURAActionPerformed
   
        sumaPrecios();
        
        
        ////////////////////FECHA///////////////////////
        
        
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);
        System.out.println("Fecha Actual: "
                           + dia + "/" + (mes+1) + "/" + año);
        System.out.printf("Hora Actual: %02d:%02d:%02d %n",
                                              hora, minuto, segundo);
        
        
        ////////////FECHA//////////////////////////////
        String path="";
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);


///////////////////////////////////////////////////////////////////////////////////DOCUMENTOS////////////        
        Document doc = new Document();
        try {
    
      PdfWriter.getInstance(doc, new FileOutputStream("D:\\Users\\danie\\Documents\\NetBeansProjects\\TiendaRefrescos\\FACTURAS\\"+jTNombreCliente.getText()+".pdf"));
      //PdfWriter.getInstance(doc, new FileOutputStream("C:/Users/usuario/Documents/NetBeansProjects/TiendaRefrescos/src/FACTURAS/Amor.pdf"));
        doc.open();
        PdfPTable tbl=new PdfPTable(5);
        
        
            tbl.addCell("CÓDIGO");
            tbl.addCell("NOMBRE DEL PRODUCTO");
            tbl.addCell("PRECIO");
            tbl.addCell("CANTIDAD");
            tbl.addCell("TOTALVENTAS");
            
            
             total1=(jtotalCampo1.getText());
                    
            for (int i = 0; i < jtabla.getRowCount(); i++) {
                String codigo=jtabla.getValueAt(i, 0).toString();
                String nombre=jtabla.getValueAt(i, 1).toString();
                String precio=jtabla.getValueAt(i, 2).toString();
                String cantidad=jtabla.getValueAt(i, 3).toString();
                String total=jtabla.getValueAt(i, 4).toString();
                
                      
                // jTNombreCliente.setText("Precio");       
                tbl.addCell(codigo);
                tbl.addCell(nombre);
                tbl.addCell(precio);
                tbl.addCell(cantidad);
                tbl.addCell(total);
               
                
                
            }
            JOptionPane.showMessageDialog(null, "SE HA CREADO LA FACTURA");
          int sum=sumatoria1; 
          Paragraph parrafo4 = new Paragraph("Fecha Actual: "+dia + "/" + (mes+1) + "/" + año );
          Paragraph parrafo5 = new Paragraph("Hora Actual: "+hora+":"+minuto+":"+segundo );
          Paragraph parrafo6 = new Paragraph("                               ");
          Paragraph parrafo7 = new Paragraph("Nit 1114457936                               ");
          Paragraph parrafo8 = new Paragraph("                               ");
          
          
Paragraph parrafo = new Paragraph("FACTURA DE COMPRA - NOMBRE DEL CLIENTE "+jTNombreCliente.getText()+"\n");
Paragraph parrafo2 = new Paragraph("                               ");
Paragraph parrafo1 = new Paragraph("FACTURA DE COMPRA \n TOTAL A PAGAR $"+sum+"\n");

           
            doc.add(parrafo4);
            doc.add(parrafo5);
            doc.add(parrafo6);
            doc.add(parrafo7);
            doc.add(parrafo8);
            doc.add(parrafo);
            doc.add(parrafo2);
            doc.add(tbl);
            doc.add(parrafo1);
            
            
            
        
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
      doc.close();
        
        
        

        
      //jtotalCampo1.setText("");
      
      try
        {
            
           for(int i=0; i<jtabla.getRowCount();i++)
          { 
          Class.forName("com.mysql.jdbc.Driver");
          Connection conexion=DriverManager.getConnection("jdbc:mysql://sql10.freesqldatabase.com:3306/sql10292471", "sql10292471", "5smwscQGBg");
          PreparedStatement ps= conexion.prepareStatement("insert into inventario1 values(?,?,?,?,?,?)");
          
          ps.setObject(1, "SUCURSAL 1");
          ps.setObject(2,(jtabla.getValueAt(i, 0)));
          ps.setObject(3, jtabla.getValueAt(i, 1));
          ps.setObject(4,jtabla.getValueAt(i, 2));
          ps.setObject(5, jtabla.getValueAt(i, 3));
          ps.setObject(6, jtabla.getValueAt(i, 4));
          
          
         
          ps.execute();
          conexion.close();
          JOptionPane.showMessageDialog(null, "ENTRO BASE DATOS");
          }
          
             
      
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null," <html><h1> CAMPO VACIO"+e);
            System.out.println("error  "+e);
          
        }
      
        /////////////////////////////////////////////////////////////////////////////////////////////////////
      
      
       
        JOptionPane.showMessageDialog(null, "<html><h1>  TOTAL A PAGAR = $ "+sumatoria1+" \n"+"<html><h1> GRACIAS POR SU COMPRA");
        sumatoria1=0;
        //jtotalCampo1.setText("0");
       
        
        DefaultTableModel modelo = (DefaultTableModel) jtabla.getModel();
            while(modelo.getRowCount()>0)modelo.removeRow(0);
            
            
            
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////777
         try {
            String url="D:\\Users\\danie\\Documents\\NetBeansProjects\\TiendaRefrescos\\FACTURAS\\"+jTNombreCliente.getText()+".pdf";
            ProcessBuilder p=new ProcessBuilder();
            p.command("cmd.exe","/C",url);
            p.start();
            
        
        } catch (IOException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          jTNombreCliente.setText("");   
    }//GEN-LAST:event_jGENERARFACTURAActionPerformed

    public void sumaPrecios() {
        //Aquí sumo los valores de la fila para colocarlos en el JTextField totalCampo
        int totalRow = jtabla.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            sumatoria = Integer.parseInt(String.valueOf(jtabla.getValueAt(i, 4)));
            sumatoria1 += sumatoria;
        }
        jtotalCampo1.setText(String.valueOf(sumatoria1));
        
    }
    
    private void jCPRODUCTOSComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCPRODUCTOSComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPRODUCTOSComponentHidden

    private void jCPRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPRODUCTOSActionPerformed
   
   jCPRODUCTOS.getSelectedItem();
    }//GEN-LAST:event_jCPRODUCTOSActionPerformed

    public void eliminarPedido(JTable tblDetalle) {
        modelo = (DefaultTableModel) tblDetalle.getModel();
        int fila = tblDetalle.getSelectedRow();
        if (fila >= 0) {
           int []filasselec  = tblDetalle.getSelectedRows();
           for (int i=0; i<filasselec.length;i++)
           {
            modelo.removeRow(filasselec.length);
           
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
       

removeSelectedRows(jtabla);
    }//GEN-LAST:event_jbCancelarActionPerformed

    

    public void removeSelectedRows(JTable table){
   DefaultTableModel model = (DefaultTableModel) this.jtabla.getModel();
   int[] rows = table.getSelectedRows();
   for(int i=0;i<rows.length;i++){
     model.removeRow(rows[i]-i);
   }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Historial dialog = new Historial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAGREGARCARRO;
    private javax.swing.JComboBox<String> jCPRODUCTOS;
    private javax.swing.JButton jGENERARFACTURA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTNIT;
    private javax.swing.JTextField jTNombreCliente;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jblimpiar;
    private javax.swing.JLabel jlFoto;
    private javax.swing.JLabel jlcliente1;
    private javax.swing.JLabel jlcliente2;
    private javax.swing.JLabel jlcodigo1;
    private javax.swing.JLabel jlcodigo2;
    private javax.swing.JTable jtabla;
    private javax.swing.JLabel jtotalCampo;
    private javax.swing.JLabel jtotalCampo1;
    // End of variables declaration//GEN-END:variables
}
